local locale = require("utils.locale")

function init(self)
	msg.post("main:/router", "switch_screen", {screen = "splash"})
	locale.init()
	print(locale.language)
	print(locale.languages[locale.language].LANGUAGE_NAME)
end

function final(self)
	
end

function update(self, dt)
	
end

function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)
	
end

function on_reload(self)


end
