local defui = require "defui.defui"


function init(self)
	msg.post(".", "acquire_input_focus")
end


function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "enable")
	end
end

function on_input(self, action_id, action)
	defui:button("btn_start", action_id, action, function()
		msg.post("@system:", "toggle_profile")
	end)
	defui:button("btn_info", action_id, action, function()
		print("hi")
	end)
end
